language: rust
rust:
  - stable

jobs:
  include:
   - os: linux
     arch: amd64
     script: /usr/lib/postgresql/12/bin/pg_ctl -D /var/lib/postgresql/12/main -l logfile start
   - os: linux
     arch: arm64
     addons:
       apt:
       packages:
         - postgresql

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_cache:
  - rm -rfv target/debug/incremental/lemmy_server-*
  - rm -rfv target/debug/.fingerprint/lemmy_server-*
  - rm -rfv target/debug/build/lemmy_server-*
  - rm -rfv target/debug/deps/lemmy_server-*
  - rm -rfv target/debug/lemmy_server.d
  - cargo clean
before_script:
  - sudo runuser -l  postgres -c "psql -c \"create user lemmy with password 'password' superuser;\""
  - sudo runuser -l  postgres -c "psql -c 'create database lemmy with owner lemmy;'"
  - rustup component add clippy --toolchain stable-x86_64-unknown-linux-gnu
before_install:
  - cd server
script:
  # Default checks, but fail if anything is detected
  - cargo build
  - cargo clippy -- -D clippy::style -D clippy::correctness -D clippy::complexity -D clippy::perf
  - cargo install diesel_cli --no-default-features --features postgres --force
  - diesel migration run
  - cargo test
env:
  global:
    - DATABASE_URL=postgres://lemmy:password@localhost:5432/lemmy
    - RUST_TEST_THREADS=1
addons:
  apt:
    packages:
    - postgresql
  postgresql: 9.5
env:
  global:
  - PGPORT=5433
#services:
#  - postgresql
